// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package mree.cloud.music.player.common.model.onedrive;

import com.google.gson.annotations.SerializedName;

import mree.cloud.music.player.common.model.SongInfo;

public class Audio {

    @SerializedName("album")
    public String Album;
    @SerializedName("albumArtist")
    public String AlbumArtist;
    @SerializedName("artist")
    public String Artist;
    @SerializedName("bitrate")
    public Long Bitrate;
    @SerializedName("composers")
    public String Composers;
    @SerializedName("copyright")
    public String Copyright;
    @SerializedName("disc")
    public Integer Disc;
    @SerializedName("discCount")
    public Integer DiscCount;
    @SerializedName("duration")
    public Long Duration;
    @SerializedName("genre")
    public String Genre;
    @SerializedName("hasDrm")
    public Boolean HasDrm;
    @SerializedName("isVariableBitrate")
    public Boolean IsVariableBitrate;
    @SerializedName("title")
    public String Title;
    @SerializedName("track")
    public Long Track;
    @SerializedName("trackCount")
    public Long TrackCount;
    @SerializedName("year")
    public Long Year;

    public SongInfo toInfo() {
        SongInfo si = new SongInfo();
        si.setAlbum(Album);
        si.setAlbumArtist(AlbumArtist);
        si.setArtist(Artist);
        si.setBitrate(Bitrate);
        si.setComposers(Composers);
        si.setCopyright(Copyright);
        si.setDisc(Disc);
        si.setDiscCount(DiscCount);
        si.setDuration(Duration);
        si.setGenre(Genre);
        si.setHasDrm(HasDrm);
        si.setIsVariableBitrate(IsVariableBitrate);
        si.setTitle(Title);
        si.setTrack(Track);
        si.setTrackCount(TrackCount);
        si.setYear(Year);
        return si;
    }
}
