// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package mree.cloud.music.player.common.model.onedrive;

import com.google.gson.annotations.SerializedName;


public class Photo {

    @SerializedName("cameraMake")
    public String CameraMake;
    @SerializedName("cameraModel")
    public String CameraModel;
    @SerializedName("exposureDenominator")
    public Double ExposureDenominator;
    @SerializedName("exposureNumerator")
    public Double ExposureNumerator;
    @SerializedName("focalLength")
    public Double FocalLength;
    @SerializedName("fNumber")
    public Double FNumber;
    @SerializedName("takenDateTime")
    public String TakenDateTime;

}
