// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package mree.cloud.music.player.common.model.onedrive;

import com.google.gson.annotations.SerializedName;

public class SharingLink {

    @SerializedName("application")
    public Identity Application;
    @SerializedName("token")
    public String Token;
    @SerializedName("type")
    public String Type;
    @SerializedName("webUrl")
    public String WebUrl;

}
