// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package mree.cloud.music.player.common.model.onedrive;

import com.google.gson.annotations.SerializedName;

public class ThumbnailSet {

    @SerializedName("id")
    public String Id;
    @SerializedName("large")
    public Thumbnail Large;
    @SerializedName("medium")
    public Thumbnail Medium;
    @SerializedName("small")
    public Thumbnail Small;
    @SerializedName("source")
    public Thumbnail Source;

}
