// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package mree.cloud.music.player.common.model.onedrive;

import com.google.gson.annotations.SerializedName;

public class Thumbnail {

    @SerializedName("content")
    public Object Content;
    @SerializedName("height")
    public Integer Height;
    @SerializedName("url")
    public String Url;
    @SerializedName("width")
    public Integer Width;

}
