// Auto-generated by OneDriveClassify on Wednesday, March 25, 2015
//    from https://api.onedrive.com/v1.0/$metadata

package mree.cloud.music.player.common.model.onedrive;

import com.google.gson.annotations.SerializedName;

import java.util.List;

public class UploadSession {

    @SerializedName("uploadUrl")
    public String UploadUrl;
    @SerializedName("expirationDateTime")
    public String ExpirationDateTime;
    @SerializedName("nextExpectedRanges")
    public List<String> NextExpectedRanges;

}
